strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

trigger:
- master

pool:
  vmImage: $(imageName)

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK (based on global.json)'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
    installationPath: $(Agent.ToolsDirectory)/dotnet
- bash: ./build.sh
  condition: or( eq( variables['Agent.OS'], 'Darwin' ), eq( variables['Agent.OS'], 'Linux' ))
  displayName: 'build.sh'
- powershell: .\build.cmd
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'build.cmd'